#!/usr/bin/env bash
#bash script to manage my process
#if [ "$1" == "start" ]; then
#    ./manage_my_process &
#    echo $$ > /var/run/my_process.pid
#    echo "manage_my_process started"
#elif [ "$1" == "stop" ]; then
#    pkill -f ./manage_my_process
#    sudo rm /var/run/my_process.pid
#    echo "manage_my_process stopped"
#elif [ "$1" == "restart" ]; then
#    pkill -f ./manage_my_process
#    sudo rm /var/run/my_process.pid
#    ./manage_my_process &
#    echo $$ > /var/run/my_process.pid
#    echo "manage_my_process restarted"
#else
#    echo "Usage: manage_my_process {start|stop|restart}"
#fi
on() {
	./manage_my_process & echo $! > /var/run/my_process.pid
}

off() {
	sudo pkill -f "./manage_my_process" & rm /var/run/my_process.pid
}

case $1 in
	start) on; echo "manage_my_process started";;
	stop) off; echo "manage_my_process stopped";;
	restart) off; on; echo "manage_my_process restarted";;
	*) echo "Usage: manage_my_process {start|stop|restart}";;
esac
